#!/usr/bin/env python3
"""Solve xArm6/OAK-D-SR eye-in-hand data collected by this package."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import cv2
import numpy as np

from .geometry import (
    inverse_transform,
    rotation_angle_deg,
    transform_from_rt,
)


def load_samples(path: Path):
    with np.load(path, allow_pickle=False) as archive:
        base_to_tcp = np.asarray(archive["base_to_tcp"], dtype=float)
        camera_to_board = np.asarray(archive["camera_to_board"], dtype=float)
        reprojection_errors = np.asarray(archive["reprojection_error_px"], dtype=float)
        marker_counts = np.asarray(archive["marker_count"], dtype=int)
        metadata = json.loads(str(archive["metadata_json"].item()))
    if len(base_to_tcp) != len(camera_to_board):
        raise ValueError("base_to_tcp and camera_to_board have different sample counts")
    if len(base_to_tcp) < 8:
        raise ValueError("at least 8 samples are required")
    return base_to_tcp, camera_to_board, reprojection_errors, marker_counts, metadata


def solve(transforms_base_tcp: np.ndarray, transforms_camera_board: np.ndarray, indices: np.ndarray):
    """Return tcp->camera and base->board for B*T*C = constant.

    OpenCV expects camera->world and gripper->base.  Here the static world is
    the AprilTag board, B is base->tcp and C is camera->board.
    """
    base_to_tcp = [transforms_base_tcp[index] for index in indices]
    camera_to_board = [transforms_camera_board[index] for index in indices]
    gripper_to_base = [inverse_transform(item) for item in base_to_tcp]
    r_world_base, t_world_base, r_camera_gripper, t_camera_gripper = cv2.calibrateRobotWorldHandEye(
        [item[:3, :3] for item in camera_to_board],
        [item[:3, 3].reshape(3, 1) for item in camera_to_board],
        [item[:3, :3] for item in gripper_to_base],
        [item[:3, 3].reshape(3, 1) for item in gripper_to_base],
        method=cv2.CALIB_ROBOT_WORLD_HAND_EYE_SHAH,
    )
    base_to_board = inverse_transform(transform_from_rt(r_world_base, t_world_base))
    tcp_to_camera = inverse_transform(transform_from_rt(r_camera_gripper, t_camera_gripper))
    return tcp_to_camera, base_to_board


def residuals(base_to_tcp, camera_to_board, tcp_to_camera, base_to_board):
    translation_mm = []
    rotation_deg = []
    for base_tcp, camera_board in zip(base_to_tcp, camera_to_board):
        predicted = base_tcp @ tcp_to_camera @ camera_board
        translation_mm.append(float(np.linalg.norm(predicted[:3, 3] - base_to_board[:3, 3]) * 1000.0))
        rotation_deg.append(rotation_angle_deg(predicted, base_to_board))
    return np.asarray(translation_mm), np.asarray(rotation_deg)


def robust_limit(values: np.ndarray, floor: float) -> float:
    median = float(np.median(values))
    mad = float(np.median(np.abs(values - median)))
    return max(floor, median + 3.5 * 1.4826 * mad)


def orientation_diversity_deg(base_to_tcp: np.ndarray) -> float:
    reference = base_to_tcp[0]
    return max(rotation_angle_deg(reference, item) for item in base_to_tcp[1:]) if len(base_to_tcp) > 1 else 0.0


def solve_with_outlier_rejection(base_to_tcp, camera_to_board, min_samples: int):
    active = np.arange(len(base_to_tcp), dtype=int)
    removed = []
    for _ in range(4):
        tcp_to_camera, base_to_board = solve(base_to_tcp, camera_to_board, active)
        translation_mm, rotation_deg = residuals(base_to_tcp, camera_to_board, tcp_to_camera, base_to_board)
        active_translation = translation_mm[active]
        active_rotation = rotation_deg[active]
        translation_limit = robust_limit(active_translation, floor=2.5)
        rotation_limit = robust_limit(active_rotation, floor=0.8)
        bad = active[(active_translation > translation_limit) | (active_rotation > rotation_limit)]
        if len(bad) == 0 or len(active) - len(bad) < min_samples:
            break
        active = np.asarray([index for index in active if index not in set(bad)], dtype=int)
        removed.extend(int(index) for index in bad)
    tcp_to_camera, base_to_board = solve(base_to_tcp, camera_to_board, active)
    translation_mm, rotation_deg = residuals(base_to_tcp, camera_to_board, tcp_to_camera, base_to_board)
    return tcp_to_camera, base_to_board, active, removed, translation_mm, rotation_deg


def write_yaml(path: Path, result: dict):
    transform = result["tcp_to_camera"]
    lines = [
        "# Generated by xarm_oak_handeye.solve_eye_in_hand",
        f"parent_frame: {result['tcp_frame']}",
        f"child_frame: {result['camera_frame']}",
        "translation_m:",
    ]
    lines.extend(f"  - {value:.12f}" for value in transform["translation_m"])
    lines.append("rotation_xyzw:")
    lines.extend(f"  - {value:.12f}" for value in transform["rotation_xyzw"])
    lines.append("matrix_row_major:")
    lines.extend("  - [" + ", ".join(f"{value:.12f}" for value in row) + "]" for row in transform["matrix"])
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def result_transform(transform):
    from .geometry import rotation_to_quaternion

    return {
        "translation_m": [float(value) for value in transform[:3, 3]],
        "rotation_xyzw": [float(value) for value in rotation_to_quaternion(transform[:3, :3])],
        "matrix": [[float(value) for value in row] for row in transform],
    }


def make_parser():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--samples", required=True, type=Path)
    parser.add_argument("--output", type=Path, default=None, help="default: result next to samples")
    parser.add_argument("--min-samples", type=int, default=8)
    parser.add_argument("--allow-low-diversity", action="store_true")
    return parser


def main(argv=None):
    args = make_parser().parse_args(argv)
    base_to_tcp, camera_to_board, reproj, markers, metadata = load_samples(args.samples)
    diversity = orientation_diversity_deg(base_to_tcp)
    if diversity < 20.0 and not args.allow_low_diversity:
        raise RuntimeError(
            f"orientation diversity is only {diversity:.1f} deg; collect poses spanning at least 20 deg "
            "or explicitly pass --allow-low-diversity"
        )
    tcp_to_camera, base_to_board, active, removed, translation_mm, rotation_deg = solve_with_outlier_rejection(
        base_to_tcp, camera_to_board, args.min_samples
    )
    if len(active) < args.min_samples:
        raise RuntimeError("outlier rejection left too few samples")
    output = args.output or args.samples.with_name("eye_in_hand_result.json")
    result = {
        "schema": "xarm_oak_handeye_eye_in_hand_result_v1",
        "mode": "eye_in_hand",
        "base_frame": metadata["base_frame"],
        "tcp_frame": metadata["tcp_frame"],
        "camera_frame": metadata["camera_frame"],
        "sample_file": str(args.samples),
        "camera": {
            "socket": metadata["camera_socket"],
            "image_size": metadata["image_size"],
            "matrix": metadata["camera_matrix"],
            "distortion": metadata["distortion"],
        },
        "board": {
            "dictionary": metadata["dictionary"],
            "grid_size": metadata["grid_size"],
            "tag_size_m": metadata["tag_size_m"],
            "tag_gap_m": metadata["tag_gap_m"],
            "board_extent_m": metadata["board_extent_m"],
        },
        "tcp_to_camera": result_transform(tcp_to_camera),
        "base_to_board": result_transform(base_to_board),
        "quality": {
            "sample_count": int(len(base_to_tcp)),
            "used_sample_indices_zero_based": [int(index) for index in active],
            "rejected_sample_indices_zero_based": sorted(set(removed)),
            "orientation_diversity_deg": float(diversity),
            "mean_tag_count": float(np.mean(markers[active])),
            "mean_pnp_reprojection_error_px": float(np.mean(reproj[active])),
            "handeye_translation_residual_mm_rms": float(np.sqrt(np.mean(translation_mm[active] ** 2))),
            "handeye_rotation_residual_deg_rms": float(np.sqrt(np.mean(rotation_deg[active] ** 2))),
            "handeye_translation_residual_mm_max": float(np.max(translation_mm[active])),
            "handeye_rotation_residual_deg_max": float(np.max(rotation_deg[active])),
        },
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, indent=2, ensure_ascii=True) + "\n", encoding="ascii")
    write_yaml(output.with_suffix(".yaml"), result)
    print(f"result: {output}")
    print(f"tcp -> camera ({result['tcp_frame']} -> {result['camera_frame']}), metres:")
    print(np.array2string(tcp_to_camera, precision=8, suppress_small=True))
    print(
        "quality: "
        f"used={len(active)}/{len(base_to_tcp)}, "
        f"orientation_span={diversity:.1f} deg, "
        f"translation_rms={result['quality']['handeye_translation_residual_mm_rms']:.3f} mm, "
        f"rotation_rms={result['quality']['handeye_rotation_residual_deg_rms']:.3f} deg"
    )


if __name__ == "__main__":
    main()
