/**:
  ros__parameters:
    filter1:
      name: angular_bounds
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -1.5708   # -90 deg, front only
        upper_angle: 1.5708    # +90 deg, front only
