/**:
  ros__parameters:
    filter1:
      name: angular_bounds_slam
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -2.1817   # -125 deg, 250-deg FOV for AMCL localization
        upper_angle: 2.1817    # +125 deg, 250-deg FOV for AMCL localization
