yesense_pub:
    ros__parameters:
        serial_port: "/dev/wheeltec_IMU"
        baud_rate: 460800
        frame_id: "gyro_link"
        driver_type: "ros_serial"
        imu_topic_ros: "imu/data"
        imu_topic: "imu_data"
        imu_output_rate_hz: 50.0
        gyro_deadband_rad_s: 0.05
        gyro_bias_calibration_samples: 400
        device_ip: 192.168.1.199                #源ip
        device_port: 2368                        #目的端口号
        device_ip_difop: 192.168.1.102           #目的ip
        difop_port: 2369                        #源端口号
        add_multicast: false                    #是否启动组播
        group_ip: 224.1.1.2                      #组播ip
